# Generated by Django 5.1 on 2024-08-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog_id',
        ),
    ]
